[[section-solution-strategy]]
== Lösungsstrategie

Dieser Abschnitt beschäftigt sich mit der Lösungsstrategie dieser Architektur. Hierbei wird näher auf den Einstieg, dem Aufbau dem Calculator und der Anbindung zwischen Sytemen eingegangen.

Dieser Abschnitt enthält einen stark verdichteten Architekturüberblick. Eine Gegenüberstellung der wichtigsten Ziele und Lösungsansätze.


=== Einstieg in die Lösungsstrategie

Die folgende Tabelle wurde auf Methoden aufgebaut, welche die Lösung des Systems erleichtern soll.
[role="arc42help"]
****

|===
|Qualitätsziel |Ansätze in der Architekur

|Funktionalität
|

|Effizienz
|Column 2, row 2

|Einfacher Aufbau
|Column 2, row 3

|schönes Design
|Column 2, row 4

|gute Daten
|Column 2, row 5

|===
.Inhalt
Kurzer Überblick über die grundlegenden Entscheidungen und Lösungsansätze, die Entwurf und Implementierung des Systems prägen.
Hierzu gehören:

* Technologieentscheidungen
* Entscheidungen über die Top-Level-Zerlegung des Systems, beispielsweise die Verwendung gesamthaft prägender Entwurfs- oder Architekturmuster,
* Entscheidungen zur Erreichung der wichtigsten Qualitätsanforderungen sowie
* relevante organisatorische Entscheidungen, beispielsweise für bestimmte Entwicklungsprozesse oder Delegation bestimmter Aufgaben an andere Stakeholder.

.Motivation
Diese wichtigen Entscheidungen bilden wesentliche „Eckpfeiler“ der Architektur.
Von ihnen hängen viele weitere Entscheidungen oder Implementierungsregeln ab.

.Form
Fassen Sie die zentralen Entwurfsentscheidungen *kurz* zusammen.
Motivieren Sie, ausgehend von Aufgabenstellung, Qualitätszielen und Randbedingungen, was Sie entschieden haben und warum Sie so entschieden haben.
Vermeiden Sie redundante Beschreibungen und verweisen Sie eher auf weitere Ausführungen in Folgeabschnitten.
****

=== Der Aufbau
[role="arc42help"]
****

|===
|Header 1 |Header 2

|Column 1, row 1
|Column 2, row 1

|Column 1, row 2
|Column 2, row 2

|Column 1, row 3
|Column 2, row 3

|Column 1, row 4
|Column 2, row 4

|Column 1, row 5
|Column 2, row 5

|Column 1, row 6
|Column 2, row 6

|Column 1, row 7
|Column 2, row 7
|===
.Inhalt
Kurzer Überblick über die grundlegenden Entscheidungen und Lösungsansätze, die Entwurf und Implementierung des Systems prägen.
Hierzu gehören:

* Technologieentscheidungen
* Entscheidungen über die Top-Level-Zerlegung des Systems, beispielsweise die Verwendung gesamthaft prägender Entwurfs- oder Architekturmuster,
* Entscheidungen zur Erreichung der wichtigsten Qualitätsanforderungen sowie
* relevante organisatorische Entscheidungen, beispielsweise für bestimmte Entwicklungsprozesse oder Delegation bestimmter Aufgaben an andere Stakeholder.

.Motivation
Diese wichtigen Entscheidungen bilden wesentliche „Eckpfeiler“ der Architektur.
Von ihnen hängen viele weitere Entscheidungen oder Implementierungsregeln ab.

.Form
Fassen Sie die zentralen Entwurfsentscheidungen *kurz* zusammen.
Motivieren Sie, ausgehend von Aufgabenstellung, Qualitätszielen und Randbedingungen, was Sie entschieden haben und warum Sie so entschieden haben.
Vermeiden Sie redundante Beschreibungen und verweisen Sie eher auf weitere Ausführungen in Folgeabschnitten.
****

=== Die Berechnung
[role="arc42help"]
****

|===
|Header 1 |Header 2

|Column 1, row 1
|Column 2, row 1

|Column 1, row 2
|Column 2, row 2

|Column 1, row 3
|Column 2, row 3

|Column 1, row 4
|Column 2, row 4

|Column 1, row 5
|Column 2, row 5

|Column 1, row 6
|Column 2, row 6

|Column 1, row 7
|Column 2, row 7
|===
.Inhalt
Kurzer Überblick über die grundlegenden Entscheidungen und Lösungsansätze, die Entwurf und Implementierung des Systems prägen.
Hierzu gehören:

* Technologieentscheidungen
* Entscheidungen über die Top-Level-Zerlegung des Systems, beispielsweise die Verwendung gesamthaft prägender Entwurfs- oder Architekturmuster,
* Entscheidungen zur Erreichung der wichtigsten Qualitätsanforderungen sowie
* relevante organisatorische Entscheidungen, beispielsweise für bestimmte Entwicklungsprozesse oder Delegation bestimmter Aufgaben an andere Stakeholder.

.Motivation
Diese wichtigen Entscheidungen bilden wesentliche „Eckpfeiler“ der Architektur.
Von ihnen hängen viele weitere Entscheidungen oder Implementierungsregeln ab.

.Form
Fassen Sie die zentralen Entwurfsentscheidungen *kurz* zusammen.
Motivieren Sie, ausgehend von Aufgabenstellung, Qualitätszielen und Randbedingungen, was Sie entschieden haben und warum Sie so entschieden haben.
Vermeiden Sie redundante Beschreibungen und verweisen Sie eher auf weitere Ausführungen in Folgeabschnitten.
****

=== Anbindung (Datenbank, Frontend, Backend)
[role="arc42help"]
****

|===
|Header 1 |Header 2

|Column 1, row 1
|Column 2, row 1

|Column 1, row 2
|Column 2, row 2

|Column 1, row 3
|Column 2, row 3

|Column 1, row 4
|Column 2, row 4

|Column 1, row 5
|Column 2, row 5

|Column 1, row 6
|Column 2, row 6

|Column 1, row 7
|Column 2, row 7
|===
.Inhalt
Kurzer Überblick über die grundlegenden Entscheidungen und Lösungsansätze, die Entwurf und Implementierung des Systems prägen.
Hierzu gehören:

* Technologieentscheidungen
* Entscheidungen über die Top-Level-Zerlegung des Systems, beispielsweise die Verwendung gesamthaft prägender Entwurfs- oder Architekturmuster,
* Entscheidungen zur Erreichung der wichtigsten Qualitätsanforderungen sowie
* relevante organisatorische Entscheidungen, beispielsweise für bestimmte Entwicklungsprozesse oder Delegation bestimmter Aufgaben an andere Stakeholder.

.Motivation
Diese wichtigen Entscheidungen bilden wesentliche „Eckpfeiler“ der Architektur.
Von ihnen hängen viele weitere Entscheidungen oder Implementierungsregeln ab.

.Form
Fassen Sie die zentralen Entwurfsentscheidungen *kurz* zusammen.
Motivieren Sie, ausgehend von Aufgabenstellung, Qualitätszielen und Randbedingungen, was Sie entschieden haben und warum Sie so entschieden haben.
Vermeiden Sie redundante Beschreibungen und verweisen Sie eher auf weitere Ausführungen in Folgeabschnitten.
****

